# Generated by Django 4.1.2 on 2022-10-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(null=True)),
                ('invoicedata', models.DateTimeField(auto_now=True)),
                ('itemid', models.PositiveIntegerField(null=True)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('invoicetotal', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
